#!/usr/bin/env groovy
library('cicd-shared-lib-dev@1.0.0') _

import java.text.SimpleDateFormat

node("${NODE_INTEGRATION_TEAM}") {
//node("dev-slave03-10.1.16.22") {
    // =================================================================================
    /**
     * TODO: Chi thay doi 2 thong tin tren tuong ung voi project
     *
     * project_name: Name of project
     * kubernetes_namespace: namespace of K8S
     */
    def project_name = "apartment-price-prediction"
    def kubernetes_namespace = "dev-edp-bigdata"

    // ===================================================================================
    def image_version = "1.0.1"
    def chart_version = "0.1.${BUILD_NUMBER}"
    def environment = "L02"
    def secret_key = "${project_name}"
    def secret_value =  sh(script: "echo -n '${secret_key}' | sha1sum | head -c 40", returnStdout: true)
    def harbor_host = vault path: "cicd/harbor", key: "harbor_dev", credentialsId: "vault-token-dev", engineVersion: "2"
    def helm_template = vault path: "cicd/helm", key: "helm_template_common", credentialsId: "vault-token-dev", engineVersion: "2"
    def helm_host_argocd = "argocd-helm-dev"
    def docker_prefix = "${harbor_host}/${kubernetes_namespace}"
    // ===================================================================================

    /**
     * TODO: Chon luong deploy
     * Deploy theo luong argocd : CICD-ARGOCD
     * Deploy theo luong helm : CICD-HELM
     */
    def Options = "CICD-HELM"
    def sub_path = "dev"

    // ===================================================================================

    ci_common(project_name, docker_prefix, image_version, harbor_host, helm_template, Options, sub_path)
    try {
        def arrProject = environment.split(' ')
        def stages = [failFast: true]
        if(arrProject.length > 0 ){
            for (int i = 0; i < arrProject.length; i++) {
                def env = arrProject[i];
                switch(env) {
                    case "L01":
                        helm_host = "${helm_host_argocd}-${env}"
                        env_argocd = "l01"
                        break
                    case "L02":
                        helm_host = "${helm_host_argocd}-${env}"
                        env_argocd = "l02"
                        break
                    case "L03":
                        helm_host = "${helm_host_argocd}-${env}"
                        env_argocd = "l03"
                        break
                    case "L04":
                        helm_host = "${helm_host_argocd}-${env}"
                        env_argocd = "l04"
                        break
                    case "L03C01":
                        helm_host = "${helm_host_argocd}-${env}"
                        env_argocd = "l03c01"
                        break
                    case "L04C01":
                        helm_host = "${helm_host_argocd}-${env}"
                        env_argocd = "l04c01"
                        break
                    case "L03C02":
                        helm_host = "${helm_host_argocd}-${env}"
                        env_argocd = "l03c02"
                        break
                    case "L04C02":
                        helm_host = "${helm_host_argocd}-${env}"
                        env_argocd = "l04c02"
                        break
                }
                stage("4.Start ${arrProject[i]} Environment"){
                    script {
                        service_account_common(project_name, env, secret_key, secret_value, sub_path)
                        helm_pack_common(project_name, env, helm_host, helm_template, docker_prefix, image_version, Options, chart_version, sub_path)
                        cd_common(project_name, helm_host, arrProject, stages, docker_prefix, image_version, env, Options, kubernetes_namespace, env_argocd, chart_version) 
                    }
                }
            }
        }
        parallel stages
    } catch (Exception ex) {
        currentBuild.result = "Failed"
        throw ex
    }
}

def ci_common(def project_name, def docker_prefix, def image_version, def harbor_host, def helm_template, def Options, def sub_path) {
    stage('Git Clone ') {
        script { ci_common_java () }
    }

    stage('Build image') {
        def nexus_python_index_url="${nexus_python_index_url_12_177}"
        def nexus_python_trusted_host="${nexus_python_trusted_host_12_177}"
        withCredentials([usernamePassword(credentialsId: 'nexus_ocr', usernameVariable: 'username', passwordVariable: 'password')]) {
            app = docker.build("${docker_prefix}/${project_name}:${image_version}","-f ./cicd/${sub_path}/Dockerfile \
            --build-arg NEXUS_USER=$username \
            --build-arg NEXUS_PASSWORD=$password \
            --build-arg NEXUS_PYTHON_INDEX_URL=$nexus_python_index_url \
            --build-arg NEXUS_PYTHON_TRUSTED_HOST=$nexus_python_trusted_host .")
            }
    }
        
    stage('Push image') {
        docker.withRegistry("http://${harbor_host}/", 'harbor-private-registry') {
            app.push()
            sh "docker image rm ${docker_prefix}/${project_name}:${image_version}"
        }
    } 
}

