from .http import HTTPClientCredentials as HTTPClientCredentials
from .http import HTTPBasicClientCredentials as HTTPBasicClientCredentials
from .oauth2 import OAuth2 as OAuth2
from .oauth2 import OAuth2ClientCredentials as OAuth2ClientCredentials
from .oauth2 import OAuth2ClientCredentialsRequestForm as OAuth2ClientCredentialsRequestForm
from .oauth2 import OAuth2ClientCredentialsRequestFormStrict as OAuth2ClientCredentialsRequestFormStrict
from .oauth2 import SecurityScopes as SecurityScopes
